name: Deploy on GitHub Pages on merge
"on":
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "oxypomme"
          reponame: "GDCBriefing"
          token: ${{ secrets.GITHUB_TOKEN }}
          useyarn: true

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
